name: iso8601_duration
description: A package to format duration from ISO 8601 duration format. It can parse string in either PnYnMnDTnHnMnS or PnW format. It will return the duration in ISODuration type.
version: 1.3.0
homepage: https://github.com/inspiretechdev/iso8601_duration

environment:
  sdk: ">=2.17.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
